# Generated by Django 4.0.3 on 2022-04-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(upload_to='livros_capas', verbose_name='Capa'),
        ),
    ]
